# Site settings
title: Generations Paintball
tagline: Generations Paintball
description: Generations Paintball
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://generationspaintball.com" # the base hostname & protocol for your site

# Plugins
gems: ["jekyll-paginate"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"
